### PR TITLE
updated tests to cover all branches

### PR DESCRIPTION
**Pull request by conleyst**
added tests so that all branches are hit at least once. The actual documentation proving this still needs to be added.

### CODE REVIEW

**Comment by tylercroberts** [comment]
Hey, its saying that we  cant automatically merge and that the conflicts are too complex to fix in the web editor. Do you want to take a look at what they are and update your branch with a new commit?

**Comment by conleyst** [comment]
I think it's fixed

**Review by tylercroberts — CHANGES_REQUESTED** [review]
There's just a few of the git artifacts left behind from the conflicts you resolved. You should remove these and then we can merge. Otherwise we'll get a syntax error when we try to run.

**Comment by conleyst** [comment]
should be good

**Review by tylercroberts — APPROVED** [review]

**Pull request merged**
